---
blank_issues_enabled: false
contact_links:
    - name: ðŸ’¬ Ask a Question or Start a Discussion
      url: https://github.com/the-user-created/FERS/discussions
      about: Please use GitHub Discussions for questions, ideas, and general conversation.
